---
- name: Install
  hosts: all
  tasks:
  - name: install git
    become: true
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
        - git

  - name: clone ropository
    git: 
        repo: https://github.com/mzabolotnov/dataproc_yc.git
        dest: /home/ubuntu/dataproc_yc
        force: true
  
  - name: Replace varible jdbcHostname pq_to_ch.py
    lineinfile:
     path: /home/ubuntu/dataproc_yc/spark/pq_to_ch.py
     regexp: '^jdbcHostname = '
     line: jdbcHostname = "{{ ch_raw_link }}"
    
  - name: Replace varible jdbcHostname csv_to_ch.py
    lineinfile:
     path: /home/ubuntu/dataproc_yc/spark/csv_to_ch.py
     regexp: '^jdbcHostname = '
     line: jdbcHostname = "{{ ch_raw_link }}"
  
  - name: Replace varible jdbcHostname clickhouse-client_run.sh
    lineinfile:
     path: /home/ubuntu/dataproc_yc/spark/clickhouse-client_run.sh
     regexp: '--host'
     line: clickhouse-client --host "{{ ch_raw_link }}" \

- import_playbook: ./install_ch_client.yml
  
