---
- name: Install
  hosts: all
  tasks:
  - name: install git
    become: true
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
        - git
  - name: clone ropository
    git: 
        repo: https://github.com/mzabolotnov/dataproc_yc.git
        dest: /home/ubuntu/dataproc_yc
  - name: Replace varible jdbcHostname
    lineinfile:
     path: /home/ubuntu/dataproc_yc/spark/pq_to_ch.py
     regexp: '^jdbcHostname = '
     line: jdbcHostname = "{{ ch_raw_link }}"

  # - name: Transform log-file to parquet-file
  #   # shell: "{{ item }}"
  #   shell: "/usr/bin/spark-submit convert_to_pq.py"

  #   # loop:
  #   #    - "/usr/bin/spark-submit convert_to_pq.py"
  #   #   #  - "echo 2"
  #   args:
  #        chdir: /home/ubuntu/dataproc_yc/spark
  #       #  executable: /usr/bin/spark-submit

  #   register: spark_res

  # - name: Print return information from the previous task
  #   debug:
  #    var: spark_res.stdout
  #    verbosity: 2
  
  # - debug:
  #      msg="{{ spark_res }}"

  # - debug:
  #      msg="{{ spark_res.result.stdout_lines }}"
    # shell: set | grep SPARK >> somelog.txt
    # # shell: /usr/bin/spark-submit convert_to_pq.py
    # args:
    #       chdir: ~/dataproc_yc/spark
    #       executable: /bin/bash
    #       creates: somelog.txt

  
